[workspace]
members = ["crates/app", "crates/ui", "crates/workspace"]

default-members = ["crates/app"]
resolver = "2"

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
